-- BLACK CROWN OPS — Phase 2 persistent player intelligence
-- Apply once in a Supabase/PostgreSQL project before setting STORAGE_BACKEND=supabase.

create table if not exists public.bco_players (
    chat_id bigint primary key,
    profile jsonb not null default '{}'::jsonb,
    summary text not null default '',
    derived jsonb not null default '{}'::jsonb,
    created_at timestamptz not null default now(),
    updated_at timestamptz not null default now()
);

create table if not exists public.bco_messages (
    id bigint generated by default as identity primary key,
    chat_id bigint not null,
    role text not null,
    content text not null,
    created_at timestamptz not null default now()
);
create index if not exists bco_messages_chat_id_id_idx on public.bco_messages(chat_id, id desc);

create table if not exists public.bco_player_mistakes (
    chat_id bigint not null,
    mistake_key text not null,
    label text not null,
    count integer not null default 1 check (count > 0),
    first_seen timestamptz not null default now(),
    last_seen timestamptz not null default now(),
    evidence jsonb not null default '{}'::jsonb,
    primary key (chat_id, mistake_key)
);
create index if not exists bco_player_mistakes_rank_idx on public.bco_player_mistakes(chat_id, count desc, last_seen desc);

create table if not exists public.bco_episodes (
    id bigint generated by default as identity primary key,
    chat_id bigint not null,
    kind text not null default 'event',
    data jsonb not null default '{}'::jsonb,
    created_at timestamptz not null default now()
);
create index if not exists bco_episodes_chat_id_id_idx on public.bco_episodes(chat_id, id desc);

create table if not exists public.bco_training_sessions (
    id bigint generated by default as identity primary key,
    chat_id bigint not null,
    data jsonb not null default '{}'::jsonb,
    created_at timestamptz not null default now()
);
create index if not exists bco_training_sessions_chat_id_id_idx on public.bco_training_sessions(chat_id, id desc);

create table if not exists public.bco_progression_events (
    id bigint generated by default as identity primary key,
    chat_id bigint not null,
    data jsonb not null default '{}'::jsonb,
    created_at timestamptz not null default now()
);
create index if not exists bco_progression_events_chat_id_id_idx on public.bco_progression_events(chat_id, id desc);

create or replace function public.bco_patch_profile(p_chat_id bigint, p_patch jsonb)
returns void
language plpgsql
security definer
set search_path = public
as $$
begin
    insert into public.bco_players(chat_id, profile, updated_at)
    values (p_chat_id, coalesce(p_patch, '{}'::jsonb), now())
    on conflict (chat_id) do update
    set profile = coalesce(public.bco_players.profile, '{}'::jsonb) || coalesce(excluded.profile, '{}'::jsonb),
        updated_at = now();
end;
$$;

create or replace function public.bco_record_mistake(
    p_chat_id bigint,
    p_mistake_key text,
    p_label text,
    p_evidence jsonb default '{}'::jsonb
)
returns void
language plpgsql
security definer
set search_path = public
as $$
begin
    insert into public.bco_player_mistakes(chat_id, mistake_key, label, count, evidence)
    values (p_chat_id, p_mistake_key, p_label, 1, coalesce(p_evidence, '{}'::jsonb))
    on conflict (chat_id, mistake_key) do update
    set label = excluded.label,
        count = public.bco_player_mistakes.count + 1,
        last_seen = now(),
        evidence = coalesce(public.bco_player_mistakes.evidence, '{}'::jsonb) || coalesce(excluded.evidence, '{}'::jsonb);
end;
$$;

create or replace function public.bco_purge_player(p_chat_id bigint)
returns void
language plpgsql
security definer
set search_path = public
as $$
begin
    delete from public.bco_messages where chat_id = p_chat_id;
    delete from public.bco_player_mistakes where chat_id = p_chat_id;
    delete from public.bco_episodes where chat_id = p_chat_id;
    delete from public.bco_training_sessions where chat_id = p_chat_id;
    delete from public.bco_progression_events where chat_id = p_chat_id;
    delete from public.bco_players where chat_id = p_chat_id;
end;
$$;

-- The browser/Mini App must never access these tables directly.
alter table public.bco_players enable row level security;
alter table public.bco_messages enable row level security;
alter table public.bco_player_mistakes enable row level security;
alter table public.bco_episodes enable row level security;
alter table public.bco_training_sessions enable row level security;
alter table public.bco_progression_events enable row level security;

revoke all on function public.bco_patch_profile(bigint, jsonb) from public, anon, authenticated;
revoke all on function public.bco_record_mistake(bigint, text, text, jsonb) from public, anon, authenticated;
revoke all on function public.bco_purge_player(bigint) from public, anon, authenticated;
grant execute on function public.bco_patch_profile(bigint, jsonb) to service_role;
grant execute on function public.bco_record_mistake(bigint, text, text, jsonb) to service_role;
grant execute on function public.bco_purge_player(bigint) to service_role;
