-- BLACK CROWN v43 // CROWN INTEL snapshot + diff ledger
-- Production migration name in Supabase: crown_intel_v43_ledger

create table if not exists public.bco_game_intel_snapshots (
  id bigint generated by default as identity primary key,
  game text not null check (game in ('warzone','bo7','bf6')),
  source_url text not null,
  title text not null default '',
  published text not null default '',
  content_hash text not null,
  blocks jsonb not null default '[]'::jsonb,
  fetched_at timestamptz not null default now(),
  created_at timestamptz not null default now(),
  unique (game, content_hash)
);

create index if not exists bco_game_intel_snapshots_game_created_idx
  on public.bco_game_intel_snapshots (game, created_at desc);

create table if not exists public.bco_game_intel_changes (
  id bigint generated by default as identity primary key,
  game text not null check (game in ('warzone','bo7','bf6')),
  from_hash text not null default '',
  to_hash text not null,
  source_url text not null,
  published text not null default '',
  added_blocks jsonb not null default '[]'::jsonb,
  removed_blocks jsonb not null default '[]'::jsonb,
  categories jsonb not null default '[]'::jsonb,
  created_at timestamptz not null default now(),
  unique (game, to_hash)
);

create index if not exists bco_game_intel_changes_game_created_idx
  on public.bco_game_intel_changes (game, created_at desc);

alter table public.bco_game_intel_snapshots enable row level security;
alter table public.bco_game_intel_changes enable row level security;

-- Intentionally no anon/authenticated policies. These tables are server-owned
-- and accessed only by the existing service-role backend.
