# -*- coding: utf-8 -*-
from __future__ import annotations

from typing import Any, Mapping, Protocol


class Storage(Protocol):
    def add(self, chat_id: int, role: str, content: Any) -> None: ...
    def get(self, chat_id: int) -> list[dict]: ...
    def clear(self, chat_id: int) -> None: ...
    def stats(self, chat_id: int) -> dict: ...

    def get_profile(self, chat_id: int) -> dict[str, Any]: ...
    def set_profile(self, chat_id: int, patch: Mapping[str, Any]) -> None: ...
    def reset_profile(self, chat_id: int) -> None: ...

    def get_summary(self, chat_id: int) -> str: ...
    def set_summary(self, chat_id: int, summary: str) -> None: ...

    def add_recurring_mistake(self, chat_id: int, mistake: str) -> None: ...
    def list_recurring_mistakes(self, chat_id: int) -> list[str]: ...

    def add_training_session(self, chat_id: int, event: Mapping[str, Any]) -> None: ...
    def list_training_sessions(self, chat_id: int) -> list[dict]: ...

    def add_progression_event(self, chat_id: int, event: Mapping[str, Any]) -> None: ...
    def list_progression_events(self, chat_id: int) -> list[dict]: ...
