# -*- coding: utf-8 -*-
from __future__ import annotations

from typing import Any, Mapping, Protocol


class Storage(Protocol):
    # Canonical identity
    def resolve_telegram_identity(self, telegram_user_id: int) -> dict[str, Any]: ...

    # Working memory
    def add(self, chat_id: int, role: str, content: Any) -> None: ...
    def get(self, chat_id: int) -> list[dict]: ...
    def clear(self, chat_id: int) -> None: ...
    def stats(self, chat_id: int) -> dict: ...

    # Stable player profile
    def get_profile(self, chat_id: int) -> dict[str, Any]: ...
    def set_profile(self, chat_id: int, patch: Mapping[str, Any]) -> None: ...
    def reset_profile(self, chat_id: int) -> None: ...

    # Long-term memory / derived intelligence
    def get_summary(self, chat_id: int) -> str: ...
    def set_summary(self, chat_id: int, summary: str) -> None: ...
    def get_derived_intelligence(self, chat_id: int) -> dict[str, Any]: ...
    def set_derived_intelligence(self, chat_id: int, data: Mapping[str, Any]) -> None: ...

    # Recurring mistakes
    def add_recurring_mistake(self, chat_id: int, mistake: str) -> None: ...
    def list_recurring_mistakes(self, chat_id: int) -> list[str]: ...
    def list_mistake_stats(self, chat_id: int) -> list[dict]: ...

    # Episodic/training/progression memory
    def add_episode(self, chat_id: int, event: Mapping[str, Any]) -> None: ...
    def list_episodes(self, chat_id: int, limit: int = 20) -> list[dict]: ...
    def add_training_session(self, chat_id: int, event: Mapping[str, Any]) -> None: ...
    def list_training_sessions(self, chat_id: int) -> list[dict]: ...
    def add_progression_event(self, chat_id: int, event: Mapping[str, Any]) -> None: ...
    def list_progression_events(self, chat_id: int) -> list[dict]: ...

    # Privacy / lifecycle
    def purge_player(self, chat_id: int) -> None: ...
    def close(self) -> None: ...
